name: ev_charging_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  custom_info_window: ^1.0.1
  flutter:
    sdk: flutter
  flutter_polyline_points: ^2.1.0
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0
  page_transition: ^2.1.0
  http: ^1.2.2
  riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  bloc: ^8.1.4
  clippy_flutter: ^2.0.0-nullsafety.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/

